#!/bin/bash
echo "Just testing my sendmail gmail relay" | mail -a $1 -s "AMIGO crashlog" maxbaeten@hotmail.com
echo "Sent log file"

# Let's make a gnuplot

echo $2
echo $3


#set datafile separator "\t"
#plot $1 using 1:2 title 'Pole', \
#     $1 using 1:3 title 'Beam'
